/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  xxsubmod.c
 *  subm:  PositionControllerPan
 *  model: PositionControllerPan
 *  expmt: Jiwy-1
 *  date:  June 9, 2023
 *  time:  9:44:13 AM
 *  user:  20-sim 5.0 Student License
 *  from:  Universiteit Twente
 *  build: 5.0.2.12127
 **********************************************************/

/* Standard include files */
#include <stdlib.h>

/* 20-sim include files */
#include "Panmodel.h"
#include "Paninteg.h"
#include "xxfuncs.h"
#include "Pansubmod.h"
#include "motionprofiles.h"
#include "EulerAngles.h"

/* The submodel I/O variables */
XXInteger Pan_number_of_inputs = 2;
XXInteger Pan_number_of_outputs = 2;

/* the names of the submodel io variables
   uncomment this part if you need these names
XXString xx_input_names[] = {
	"in",
	"position"
,	NULL
};
XXString xx_output_names[] = {
	"corr",
	"out"
,	NULL
};
*/
/* This function sets the input variables from the input vector */
void PanCopyInputsToVariables (XXDouble *u)
{
	/* Copy the input vector to the input variables */
	Pan_V[7] = u[0];		/* in */
	Pan_V[8] = u[1];		/* position */

}

/* This function uses the output variables to fill the output vector */
void PanCopyVariablesToOutputs (XXDouble *y)
{
	/* Copy the output variables to the output vector */
	y[0] = 	Pan_V[6];		/* corr */
	y[1] = 	Pan_V[9];		/* out */

}

/* The initialization function for submodel */
void PanInitializeSubmodel (XXDouble *u, XXDouble *y, XXDouble t)
{
	/* Initialization phase (allocating memory) */
	Pan_initialize = XXTRUE;
	Pan_steps = 0;
	PanModelInitialize ();
	PanDiscreteInitialize ();

	/* Copy the inputs */
	Pan_time = t;
	PanCopyInputsToVariables (u);

	/* Calculate the model for the first time */
	PanCalculateInitial ();
	PanCalculateStatic ();
	PanCalculateInput ();
	PanCalculateDynamic ();
	PanCalculateOutput ();

	/* Set the outputs */
	PanCopyVariablesToOutputs (y);

	/* End of initialization phase */
	Pan_initialize = XXFALSE;
}

/* The function that calculates the submodel */
void PanCalculateSubmodel (XXDouble *u, XXDouble *y, XXDouble t)
{
	/* Copy the inputs */
	Pan_time = t;
	PanCopyInputsToVariables (u);

	/* Calculate the model */
	PanCalculateInput ();
	PanDiscreteStep ();
	PanCalculateOutput ();

	/* Copy the outputs */
	PanCopyVariablesToOutputs (y);
}

/* The termination function for submodel */
void PanTerminateSubmodel (XXDouble *u, XXDouble *y, XXDouble t)
{
	/* Copy the inputs */
	Pan_time = t;
	PanCopyInputsToVariables (u);

	/* Calculate the final model equations */
	PanCalculateFinal ();

	/* Set the outputs */
	PanCopyVariablesToOutputs (y);

	/* and terminate the model itself (releasing memory) */
	PanModelTerminate ();
	PanDiscreteTerminate ();
}

