/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  Tiltsubmod.h
 *  subm:  PositionControllerTilt
 *  model: PositionControllerTilt
 *  expmt: Jiwy-1
 *  date:  June 9, 2023
 *  time:  10:02:48 AM
 *  user:  20-sim 5.0 Student License
 *  from:  Universiteit Twente
 *  build: 5.0.2.12127
 **********************************************************/

/* This file describes the model functions
   that are supplied for computation.

   The model itself is the Tiltmodel.c file
*/

#ifndef TILT_SUBMOD_H
#define TILT_SUBMOD_H

/* Our own include files */
#include "Tiltmodel.h"

/* Submodel I/O variables */
extern XXInteger Tilt_number_of_inputs;
extern XXInteger Tilt_number_of_outputs;

/* The names of the variables as used in the arrays above */
extern XXString Tilt_input_names[];
extern XXString Tilt_output_names[];


/* The submodel functions */
void TiltInitializeSubmodel (XXDouble *u, XXDouble *y, XXDouble t);
void TiltCalculateSubmodel (XXDouble *u, XXDouble *y, XXDouble t);
void TiltTerminateSubmodel (XXDouble *u, XXDouble *y, XXDouble t);
void TiltCopyInputsToVariables (XXDouble *u);
void TiltCopyVariablesToOutputs (XXDouble *y);

#endif

