/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  motionprofiles.h
 *  model: PositionControllerPan
 *  expmt: Jiwy-1
 *  date:  June 9, 2023
 *  time:  8:50:52 AM
 *  user:  20-sim 5.0 Student License
 *  from:  Universiteit Twente
 *  build: 5.0.2.12127
 **********************************************************/

/* This file defines the functions necessary for motion profiles
   functions
*/
