/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  xxinteg.c
 *  subm:  PositionControllerPan
 *  model: PositionControllerPan
 *  expmt: Jiwy-1
 *  date:  June 9, 2023
 *  time:  9:44:13 AM
 *  user:  20-sim 5.0 Student License
 *  from:  Universiteit Twente
 *  build: 5.0.2.12127
 **********************************************************/

/* This file describes the integration methods
   that are supplied for computation.

   Currently the following methods are supported:
   * Euler
   * RungeKutta2
   * RungeKutta4
   but it is easy for the user to add their own
   integration methods with these two as an example.
*/

/* the system include files */
#include <stdlib.h>
#include <string.h>
#include <math.h>

/* our own include files */
#include "Paninteg.h"
#include "Panmodel.h"

/* global variables prototypes */
extern XXDouble Pan_time;
extern XXDouble Pan_step_size;

#define xx_STATE_SIZE 3

/*********************************************************************
 * Discrete integration method
 *********************************************************************/

/* the initialization of the Discrete integration method */
void PanDiscreteInitialize (void)
{
	/* nothing to be done */
	Pan_major = XXTRUE;
}

/* the termination of the Discrete integration method */
void PanDiscreteTerminate (void)
{
	/* nothing to be done */
}

/* the Discrete integration method itself */
void PanDiscreteStep (void)
{
	XXInteger index;

	/* for each of the supplied states */
	for (index = 0; index < xx_STATE_SIZE; index++)
	{
		/* just a move of the new state */
		Pan_s [index] = Pan_R [index];
	}
	/* increment the simulation time */
	Pan_time += Pan_step_size;

	Pan_major = XXTRUE;

	/* evaluate the dynamic part to calculate the new rates */
	PanCalculateDynamic ();
}

