/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  xxsubmod.c
 *  subm:  PositionControllerTilt
 *  model: PositionControllerTilt
 *  expmt: Jiwy-1
 *  date:  June 9, 2023
 *  time:  10:02:48 AM
 *  user:  20-sim 5.0 Student License
 *  from:  Universiteit Twente
 *  build: 5.0.2.12127
 **********************************************************/

/* Standard include files */
#include <stdlib.h>

/* 20-sim include files */
#include "Tiltmodel.h"
#include "Tiltinteg.h"
#include "xxfuncs.h"
#include "Tiltsubmod.h"

/* The submodel I/O variables */
XXInteger Tilt_number_of_inputs = 3;
XXInteger Tilt_number_of_outputs = 1;

/* the names of the submodel io variables
   uncomment this part if you need these names
XXString xx_input_names[] = {
	"corr",
	"in",
	"position"
,	NULL
};
XXString xx_output_names[] = {
	"out"
,	NULL
};
*/
/* This function sets the input variables from the input vector */
void TiltCopyInputsToVariables (XXDouble *u)
{
	/* Copy the input vector to the input variables */
	Tilt_V[8] = u[0];		/* corr */
	Tilt_V[9] = u[1];		/* in */
	Tilt_V[10] = u[2];		/* position */

}

/* This function uses the output variables to fill the output vector */
void TiltCopyVariablesToOutputs (XXDouble *y)
{
	/* Copy the output variables to the output vector */
	y[0] = 	Tilt_V[11];		/* out */

}

/* The initialization function for submodel */
void TiltInitializeSubmodel (XXDouble *u, XXDouble *y, XXDouble t)
{
	/* Initialization phase (allocating memory) */
	Tilt_initialize = XXTRUE;
	Tilt_steps = 0;
	TiltModelInitialize ();
	TiltDiscreteInitialize ();

	/* Copy the inputs */
	Tilt_time = t;
	TiltCopyInputsToVariables (u);

	/* Calculate the model for the first time */
	TiltCalculateInitial ();
	TiltCalculateStatic ();
	TiltCalculateInput ();
	TiltCalculateDynamic ();
	TiltCalculateOutput ();

	/* Set the outputs */
	TiltCopyVariablesToOutputs (y);

	/* End of initialization phase */
	Tilt_initialize = XXFALSE;
}

/* The function that calculates the submodel */
void TiltCalculateSubmodel (XXDouble *u, XXDouble *y, XXDouble t)
{
	/* Copy the inputs */
	Tilt_time = t;
	TiltCopyInputsToVariables (u);

	/* Calculate the model */
	TiltCalculateInput ();
	TiltDiscreteStep ();
	TiltCalculateOutput ();

	/* Copy the outputs */
	TiltCopyVariablesToOutputs (y);
}

/* The termination function for submodel */
void TiltTerminateSubmodel (XXDouble *u, XXDouble *y, XXDouble t)
{
	/* Copy the inputs */
	Tilt_time = t;
	TiltCopyInputsToVariables (u);

	/* Calculate the final model equations */
	TiltCalculateFinal ();

	/* Set the outputs */
	TiltCopyVariablesToOutputs (y);

	/* and terminate the model itself (releasing memory) */
	TiltModelTerminate ();
	TiltDiscreteTerminate ();
}

