/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  xxinverse.c
 *  model: PositionControllerPan
 *  expmt: Jiwy-1
 *  date:  June 9, 2023
 *  time:  9:44:13 AM
 *  user:  20-sim 5.0 Student License
 *  from:  Universiteit Twente
 *  build: 5.0.2.12127
 **********************************************************/

/* No matrix support functions are needed for this model */

